### ISSUE TITLE
ERROR on my env

### ISSUE THREAD

**Issue by h4rk8s** [galbwe/math-genealogy-scraper#2] opened 2022-04-03 06:47 UTC
hi , when I run this project ,then notice a ERROR , can't save items to database.
`2022-04-03 06:45:54 [scrapers.pipelines] ERROR: Exception while saving items to database: AttributeError("type object 'StudentAdvisor' has no attribute 'student'")`

**Comment by h4rk8s** [comment] 2022-04-03 06:48
pipelines.py L117

**Comment by galbwe** [comment] 2022-04-04 01:55
🤔  @h4rk8s what did you do to run the project?

**Comment by h4rk8s** [comment] 2022-04-04 14:41
I was preparing an article of mine, and I discovered your project by accident. I was very moved and surprised, so I just modified docker-compose [it looks like the 👇]in my mbp's docker desktop and ran it directly. [It looks like the picture below], then the shell enters the container, executes ./scripts/crawl.sh, and modifies the batch_size to see if it can succeed, but an error is reported. Then came here to ask questions and waiting for you 😢

Attatch:
"""
version: '4'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
      
  api:
    container_name: math_genealogy_scraper
    image: math_genealogy
    depends_on:
      - postgres
    
    ports:
      - 8080:8080

    environment:
      ENVIRONMENT: dev
      POSTGRES_CONNECTION_DEV: postgresql://postgres:postgres@postgres/math_genealogy

    links:
      - postgres

volumes:
  pg-dataset:
"""
![part1](https://user-images.githubusercontent.com/63350517/161568283-44bdbee9-4c10-4505-9144-5399915e7337.png)
![part2](https://user-images.githubusercontent.com/63350517/161568305-c48a3b23-ed3e-4946-8724-829a45444470.png)

**Comment by galbwe** [comment] 2022-04-05 00:37
Okay I'll take a look. This project kind of got abandoned because it was originally to help a friend with a math background transition into software development. They got a postdoc and continued pursuing academia and the project has gone by the wayside since then.

My initial guess is that you need to run the alembic migrations. At any rate, I'll see if I can get it running locally and add a README with instructions if I have any success. Feel free to open a PR if you beat me to it.

**Comment by h4rk8s** [comment] 2022-04-05 01:27
thank you for your reply. Speaking of which, I am still very emotional, because I was not familiar with postgres at first, so I also used MySQL to run it, but I also reported this error. Later, I thought it was wrong over the weekend. I should follow your way, so I used docker. I used alibic to generate sql and used DDL to build tables in postgres, but it still didn't work.

**Comment by h4rk8s** [comment] 2022-04-05 01:35
this is my DDL：
`BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);




CREATE TABLE mathematician (
    id SERIAL NOT NULL,
    name VARCHAR,
    school VARCHAR,
    graduated VARCHAR,
    thesis VARCHAR,
    country VARCHAR,
    subject VARCHAR,
    math_genealogy_url VARCHAR,
    math_sci_net_url VARCHAR,
    publications INTEGER,
    citations INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE student_advisor (
    id SERIAL NOT NULL,
    student_id INTEGER,
    advisor_id INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY(advisor_id) REFERENCES mathematician (id),
    FOREIGN KEY(student_id) REFERENCES mathematician (id)
);

INSERT INTO alembic_version (version_num) VALUES ('ffd4d2ed95e3') RETURNING alembic_version.version_num;




CREATE TABLE arxiv_paper (
    id SERIAL NOT NULL,
    title VARCHAR,
    subjects VARCHAR,
    PRIMARY KEY (id)
);

UPDATE alembic_version SET version_num='8bdaab87d45c' WHERE alembic_version.version_num = 'ffd4d2ed95e3';




ALTER TABLE arxiv_paper ADD COLUMN msc_classes VARCHAR;

UPDATE alembic_version SET version_num='73a6e35b6cee' WHERE alembic_version.version_num = '8bdaab87d45c';

COMMIT;`

**Comment by galbwe** [comment] 2022-04-05 03:34
Okay the issue is here in `db.py` line 124

```
class StudentAdvisor(BaseModel):
    __tablename__ = "student_advisor"

    id = Column(Integer, primary_key=True, autoincrement=True)
    student_id = Column(Integer, ForeignKey("mathematician.id"))
    advisor_id = Column(Integer, ForeignKey("mathematician.id"))
```

`StudentAdvisor` has `student_id` and `advisor_id` attributes, but no `student` and no `advisor`, so you get `AttributeError("type object 'StudentAdvisor' has no attribute 'student'")` when trying to access `StudentAdvisor.student`. 

At some point there must have been a relationship defined on this table to give the model `student` and `advisor` attributes, but I couldn't figure it out. The quick fix is to change the queries in `pipelines.py` to use `student_id` and `advisor_id` like so:

```python
                    student_relation = (
                        session.query(StudentAdvisor)
                        .filter(
                            (StudentAdvisor.student_id == student_id)
                            & (StudentAdvisor.advisor_id == mathematician.id)
                        )
                        .first()
                    )
```

I'll include the changes in a PR along with a README update.

**Comment by galbwe** [comment] 2022-04-05 03:46
This should now be addressed by [!3](https://github.com/galbwe/math-genealogy-scraper/pull/3). @h4rk8s try pulling the main branch and let me know if it works for you.

**Comment by h4rk8s** [comment] 2022-04-05 05:24
I just got home, I'll try it in a while, thanks for your help. I respect your work. You look like a million dollars. @galbwe

**Closed as completed** 2022-04-05 12:12 UTC
